"""Las 50 historias sociales: (categoría, título, [(pictograma, frase)], nota para el adulto)."""

CATS = {
 'salud': ('Salud y cuidado personal', 'hospital'),
 'colegio': ('En el colegio', 'escuela'),
 'emociones': ('Mis emociones', 'calma'),
 'amigos': ('Con los demás', 'amigos'),
 'casa': ('En casa', 'casa'),
 'salidas': ('Salidas y viajes', 'auto'),
}

H = [
# ---------------------------------------------------------------- SALUD (8)
('salud', 'Voy al médico', [
 ('hospital', 'A veces voy al médico para saber si mi cuerpo está sano.'),
 ('reloj_espera', 'Primero espero en la sala. Puedo mirar un libro mientras espero.'),
 ('doctor', 'El médico me saluda. Es una persona que cuida a los niños.'),
 ('termometro', 'Puede mirar mis oídos, mi garganta y escuchar mi corazón.'),
 ('respirar', 'Si me pongo nervioso, respiro despacio por la nariz.'),
 ('calma', 'Me quedo lo más quieto que puedo. Así termina más rápido.'),
 ('feliz', 'Cuando termina, volvemos a casa. ¡Lo hice muy bien!'),
], 'Lee la historia varios días antes de la cita. Puedes jugar al doctor con un peluche para practicar.'),
('salud', 'Voy al dentista', [
 ('diente', 'Mis dientes me ayudan a comer y a sonreír.'),
 ('hospital', 'El dentista es el doctor de los dientes.'),
 ('reloj_espera', 'Me siento en una silla especial que sube y baja.'),
 ('sorpresa', 'Abro la boca grande para que pueda mirar mis dientes.'),
 ('ruido', 'Algunos aparatos hacen ruido. El ruido no me hace daño.'),
 ('mano_arriba', 'Si necesito una pausa, puedo levantar la mano.'),
 ('feliz', 'Al terminar, mis dientes están limpios y sanos.'),
], 'Acordar una señal (levantar la mano) da al niño sensación de control. Pídele al dentista que la respete.'),
('salud', 'Me cortan el pelo', [
 ('tijeras_pelo', 'Cuando mi pelo crece mucho, es hora de cortarlo.'),
 ('peine', 'La persona que corta el pelo usa peine y tijeras.'),
 ('calma', 'Cortar el pelo no duele. El pelo no siente nada.'),
 ('ruido', 'Puede que use una máquina que hace ruido y cosquillas.'),
 ('auriculares', 'Si el ruido me molesta, puedo usar mis auriculares.'),
 ('reloj_espera', 'Me quedo sentado mientras cuento hasta 10 varias veces.'),
 ('feliz', 'Al terminar, me miro al espejo. ¡Me veo muy bien!'),
], 'Corta el pelo en casa primero, solo un poco, para acostumbrarlo. Lleva su juguete favorito.'),
('salud', 'Me ponen una vacuna', [
 ('jeringa', 'Las vacunas ayudan a que mi cuerpo no se enferme.'),
 ('doctor', 'Una enfermera me pondrá la vacuna en el brazo.'),
 ('nervioso', 'Puedo sentir un pinchazo pequeño. Dura muy poquito.'),
 ('adulto', 'Mamá o papá me abraza y se queda conmigo.'),
 ('respirar', 'Puedo soplar como si apagara velas mientras me la ponen.'),
 ('curita', 'Después me ponen una curita.'),
 ('feliz', 'Fui valiente. Mi cuerpo ahora está más protegido.'),
], 'No digas "no duele". Es mejor anticipar: "vas a sentir un pinchazo corto".'),
('salud', 'Me cortan las uñas', [
 ('manos', 'Mis uñas crecen todo el tiempo.'),
 ('unas', 'Cuando están largas, hay que cortarlas.'),
 ('calma', 'Cortar las uñas no duele. Las uñas no sienten.'),
 ('reloj_espera', 'Cortamos una uña a la vez. Puedo contar los dedos.'),
 ('respirar', 'Si me molesta, puedo pedir una pausa y respirar.'),
 ('si', '¡Diez dedos listos! Mis manos están limpias.'),
], 'Hazlo después del baño, cuando las uñas están más blandas. Cuenten juntos en voz alta.'),
('salud', 'Tomo mi medicina', [
 ('termometro', 'Cuando estoy enfermo, el médico puede darme medicina.'),
 ('medicina', 'La medicina ayuda a que mi cuerpo se cure.'),
 ('adulto', 'Solo tomo la medicina que me da un adulto.'),
 ('sorpresa', 'A veces tiene un sabor raro. Puedo tomarla rápido.'),
 ('vaso', 'Después puedo tomar agua.'),
 ('feliz', 'Poco a poco me voy sintiendo mejor.'),
], 'Refuerza la regla de seguridad: los medicamentos solo los da un adulto.'),
('salud', 'Me lavan el pelo', [
 ('bano_pelo', 'En el baño, a veces lavamos mi pelo.'),
 ('miedo', 'Puede que no me guste el agua en la cara.'),
 ('toalla', 'Puedo taparme los ojos con una toallita seca.'),
 ('jabon', 'El champú hace espuma. Lo enjuagamos rápido.'),
 ('reloj_espera', 'Contamos hasta 10 y el agua termina.'),
 ('feliz', 'Mi pelo queda limpio y suave.'),
], 'Una visera de baño o inclinar la cabeza hacia atrás ayuda mucho a los niños que no toleran el agua en la cara.'),

# -------------------------------------------------------------- COLEGIO (10)
('colegio', 'Mi primer día de clases', [
 ('escuela', 'Pronto voy a empezar en un colegio nuevo.'),
 ('mochila', 'Llevo mi mochila con mis cosas.'),
 ('maestra', 'Mi maestra me va a recibir y me va a ayudar.'),
 ('amigos', 'En el salón hay otros niños. Puedo conocer amigos nuevos.'),
 ('nervioso', 'Es normal sentirme nervioso el primer día.'),
 ('reloj_espera', 'Al terminar la jornada, alguien viene a buscarme.'),
 ('feliz', 'Cada día el colegio se siente más conocido.'),
], 'Si es posible, visiten el colegio antes y tomen fotos del salón y de la maestra para agregarlas a la historia.'),
('colegio', 'Cuando mamá o papá se va', [
 ('adulto', 'Mamá o papá me lleva al colegio.'),
 ('abrazo', 'Nos despedimos con un abrazo y un beso.'),
 ('triste', 'Puedo sentirme triste cuando se va. Está bien.'),
 ('maestra', 'Mi maestra me cuida mientras estoy en el colegio.'),
 ('pelota', 'Puedo jugar y aprender cosas nuevas.'),
 ('reloj_espera', 'Mamá o papá siempre vuelve a buscarme.'),
 ('feliz', 'Al final del día nos volvemos a ver.'),
], 'Despídete siempre, de forma breve y tranquila. Irse a escondidas aumenta la ansiedad.'),
('colegio', 'Levanto la mano para hablar', [
 ('maestra', 'En clase, la maestra explica cosas importantes.'),
 ('pregunta', 'A veces quiero decir algo o preguntar.'),
 ('mano_arriba', 'Primero levanto la mano y espero en silencio.'),
 ('reloj_espera', 'Puede que tenga que esperar un poquito.'),
 ('si', 'Cuando la maestra dice mi nombre, hablo.'),
 ('feliz', 'Así todos pueden escuchar y hablar por turnos.'),
], 'Practiquen en casa durante la cena: quien quiere hablar, levanta la mano.'),
('colegio', 'Hago la fila', [
 ('fila', 'En el colegio a veces hacemos fila.'),
 ('yo', 'Me pongo detrás de un compañero.'),
 ('calma', 'Dejo un espacio para no empujar.'),
 ('reloj_espera', 'Espero mi turno con mis manos quietas.'),
 ('puerta', 'Caminamos despacio, uno detrás del otro.'),
 ('feliz', 'Hacer fila ayuda a que todos lleguen seguros.'),
], 'Marcar el lugar con una cinta en el piso, en casa, ayuda a entender la distancia.'),
('colegio', 'La hora del recreo', [
 ('alarma', 'Cuando suena el timbre, es hora del recreo.'),
 ('parque', 'Salgo al patio a jugar y descansar.'),
 ('lonchera', 'Puedo comer mi merienda.'),
 ('amigos', 'Puedo jugar con mis amigos o descansar solo.'),
 ('pregunta', 'Si quiero jugar, pregunto: "¿Puedo jugar contigo?".'),
 ('alarma', 'Cuando suena el timbre otra vez, vuelvo al salón.'),
], 'Estar solo en el recreo también es válido si el niño lo necesita para regularse.'),
('colegio', 'Simulacro de sismo', [
 ('alarma', 'A veces en el colegio suena una alarma de simulacro.'),
 ('ruido', 'La alarma suena fuerte. Es para practicar.'),
 ('maestra', 'Escucho a mi maestra y hago lo que dice.'),
 ('fila', 'Salimos caminando, sin correr, en fila.'),
 ('parque', 'Esperamos todos juntos en un lugar seguro.'),
 ('feliz', 'Practicar nos ayuda a saber qué hacer.'),
], 'Si la alarma le molesta mucho, pide al colegio que te avise de la fecha y lleve auriculares.'),
('colegio', 'Trabajo en grupo', [
 ('amigos', 'A veces la maestra nos pide trabajar en grupo.'),
 ('pregunta', 'Cada uno puede dar sus ideas.'),
 ('reloj_espera', 'Escucho cuando habla mi compañero.'),
 ('si', 'Podemos elegir juntos qué hacer.'),
 ('calma', 'Si no usamos mi idea, está bien. Habrá otras veces.'),
 ('feliz', 'Juntos podemos hacer cosas geniales.'),
], 'Asignarle un rol concreto (el que reparte, el que pega) facilita la participación.'),
('colegio', 'Necesito ir al baño en clase', [
 ('inodoro', 'A veces necesito ir al baño durante la clase.'),
 ('mano_arriba', 'Levanto la mano.'),
 ('pregunta', 'Digo: "Maestra, ¿puedo ir al baño?".'),
 ('si', 'Cuando me dice que sí, voy.'),
 ('jabon', 'Me lavo las manos.'),
 ('escuela', 'Vuelvo al salón y me siento en mi lugar.'),
], 'Una tarjeta de "baño" para mostrar a la maestra ayuda a niños con poco lenguaje.'),
('colegio', 'Hoy viene otra maestra', [
 ('maestra', 'A veces mi maestra no puede venir.'),
 ('adulto', 'Otra maestra viene a cuidarnos ese día.'),
 ('sorpresa', 'Es diferente, y eso puede sentirse raro.'),
 ('libro', 'Las reglas del salón siguen siendo las mismas.'),
 ('calma', 'Puedo respirar y seguir con las actividades.'),
 ('feliz', 'Mi maestra volverá pronto.'),
], 'Pide al colegio que avise con anticipación. Los cambios anticipados se viven con menos angustia.'),
('colegio', 'Como mi lonchera en el colegio', [
 ('lonchera', 'En mi lonchera hay comida para el colegio.'),
 ('jabon', 'Antes de comer, me lavo las manos.'),
 ('silla', 'Me siento en mi lugar para comer.'),
 ('plato', 'Como despacio y mastico bien.'),
 ('ordenar', 'Al terminar, guardo todo en mi lonchera.'),
 ('feliz', 'Comer me da energía para jugar y aprender.'),
], 'Prepara la lonchera juntos el día anterior: le da anticipación y control.'),
('colegio', 'Hago mis tareas', [
 ('libro', 'Algunos días traigo tareas a casa.'),
 ('silla', 'Me siento en mi lugar de tareas.'),
 ('lapiz', 'Hago una tarea a la vez.'),
 ('reloj_espera', 'Si me canso, puedo tomar una pausa corta.'),
 ('pregunta', 'Si no entiendo, pido ayuda.'),
 ('feliz', 'Cuando termino, guardo todo. ¡Lo logré!'),
], 'Divide la tarea en partes y usa un temporizador. Celebra el esfuerzo, no solo el resultado.'),

# ------------------------------------------------------------ EMOCIONES (10)
('emociones', 'Cuando me enojo', [
 ('enojado', 'A veces me enojo. Todas las personas se enojan.'),
 ('corazon', 'Cuando me enojo, mi corazón late rápido y mi cara se calienta.'),
 ('no', 'Enojarse está bien. Pegar o romper cosas no está bien.'),
 ('respirar', 'Puedo respirar profundo: inflo la panza y suelto el aire.'),
 ('reloj_espera', 'Puedo contar hasta 10 despacio.'),
 ('adulto', 'Puedo decir "estoy enojado" o pedir ayuda.'),
 ('calma', 'Poco a poco el enojo se va.'),
], 'Practica la respiración en momentos tranquilos, no solo durante la crisis.'),
('emociones', 'Cuando estoy triste', [
 ('triste', 'A veces me siento triste.'),
 ('pregunta', 'Puedo estar triste porque algo no salió bien o extraño a alguien.'),
 ('si', 'Llorar está bien. Ayuda a sacar la tristeza.'),
 ('abrazo', 'Puedo pedir un abrazo.'),
 ('libro', 'Puedo hacer algo que me gusta, como leer o dibujar.'),
 ('feliz', 'La tristeza pasa, y luego me siento mejor.'),
], 'Valida la emoción ("veo que estás triste") antes de intentar solucionarla.'),
('emociones', 'Cuando tengo miedo', [
 ('miedo', 'A veces siento miedo.'),
 ('ruido', 'Puedo tener miedo de ruidos fuertes, de la oscuridad o de cosas nuevas.'),
 ('adulto', 'Puedo decirle a un adulto: "tengo miedo".'),
 ('abrazo', 'Un adulto puede ayudarme a sentirme seguro.'),
 ('respirar', 'Respiro despacio y aprieto mi peluche.'),
 ('calma', 'El miedo se hace más pequeño cuando lo hablo.'),
], 'Ponerle nombre al miedo lo hace más manejable. Nunca te burles de un miedo, aunque parezca pequeño.'),
('emociones', 'Cuando pierdo un juego', [
 ('pelota', 'Me gusta jugar con otros.'),
 ('si', 'En los juegos, a veces gano y a veces pierdo.'),
 ('triste', 'Cuando pierdo, puedo sentirme triste o enojado.'),
 ('respirar', 'Respiro y digo: "La próxima vez puedo ganar".'),
 ('amigos', 'Puedo felicitar al que ganó.'),
 ('feliz', 'Lo más divertido es jugar juntos.'),
], 'Juega en casa juegos cortos donde pierda a propósito y modela cómo reaccionar.'),
('emociones', 'Cuando cambian los planes', [
 ('reloj_espera', 'A veces tengo un plan para el día.'),
 ('sorpresa', 'A veces los planes cambian. Eso puede pasar.'),
 ('enojado', 'Me puedo sentir enojado o confundido. Está bien.'),
 ('adulto', 'Un adulto me explica qué va a pasar ahora.'),
 ('respirar', 'Respiro y miro el nuevo plan.'),
 ('feliz', 'El nuevo plan también puede estar bien.'),
], 'Usa una tarjeta de "cambio" o "sorpresa" en su agenda visual para practicar los imprevistos.'),
('emociones', 'Cuando hay mucho ruido', [
 ('ruido', 'Hay lugares con mucho ruido: fiestas, tiendas o la calle.'),
 ('nervioso', 'El ruido fuerte me puede molestar mucho.'),
 ('auriculares', 'Puedo ponerme mis auriculares.'),
 ('manos', 'Puedo taparme los oídos con las manos.'),
 ('puerta', 'Puedo pedir ir a un lugar más tranquilo.'),
 ('calma', 'Cuando hay menos ruido, me siento mejor.'),
], 'Lleva siempre auriculares con cancelación de ruido en salidas a lugares concurridos.'),
('emociones', 'Cuando estoy nervioso', [
 ('nervioso', 'A veces me siento nervioso.'),
 ('corazon', 'Mi panza puede sentirse rara y mis manos pueden sudar.'),
 ('pregunta', 'Puedo sentirme así antes de algo nuevo.'),
 ('respirar', 'Respiro como un globo: inflo y desinflo.'),
 ('adulto', 'Puedo contarle a alguien cómo me siento.'),
 ('calma', 'Los nervios bajan cuando sé qué va a pasar.'),
], 'Anticipar con esta historia o con fotos reduce los nervios ante situaciones nuevas.'),
('emociones', 'Puedo pedir un descanso', [
 ('nervioso', 'A veces me siento cansado o abrumado.'),
 ('mano_arriba', 'Puedo pedir un descanso.'),
 ('pregunta', 'Digo: "Necesito un descanso" o muestro mi tarjeta.'),
 ('silla', 'Voy a mi rincón tranquilo.'),
 ('reloj_espera', 'Descanso un ratito.'),
 ('feliz', 'Cuando me siento mejor, vuelvo a la actividad.'),
], 'Crea una tarjeta de "descanso" y respeta su uso: así aprende a pedirlo en lugar de explotar.'),
('emociones', 'Cuando me equivoco', [
 ('lapiz', 'A veces me equivoco.'),
 ('si', 'Todas las personas se equivocan. Así se aprende.'),
 ('triste', 'Puedo sentirme mal, y está bien.'),
 ('respirar', 'Respiro y lo intento otra vez.'),
 ('pregunta', 'Puedo pedir ayuda si la necesito.'),
 ('feliz', 'Equivocarse es parte de aprender.'),
], 'Comparte tus propios errores en voz alta: "uy, me equivoqué, lo hago otra vez".'),
('emociones', 'Cuando me dicen que no', [
 ('pregunta', 'A veces pido algo.'),
 ('no', 'A veces la respuesta es "no".'),
 ('enojado', 'Puedo sentirme triste o enojado.'),
 ('respirar', 'Respiro y acepto la respuesta.'),
 ('reloj_espera', 'Tal vez pueda tenerlo en otro momento.'),
 ('feliz', 'Puedo elegir otra cosa que también me gusta.'),
], 'Ofrece dos alternativas posibles después del "no". Elegir da sensación de control.'),

# -------------------------------------------------------------- AMIGOS (10)
('amigos', 'Saludo a las personas', [
 ('amigos', 'Cuando veo a alguien que conozco, lo saludo.'),
 ('manos', 'Puedo decir "hola" o mover la mano.'),
 ('feliz', 'Puedo mirar a la persona y sonreír.'),
 ('si', 'Si no quiero abrazar o besar, puedo chocar la mano.'),
 ('puerta', 'Cuando me voy, digo "chau" o "adiós".'),
 ('feliz', 'Saludar hace sentir bien a los demás.'),
], 'Respeta que no quiera abrazos o besos: ofrécele alternativas como chocar la mano.'),
('amigos', 'Comparto mis juguetes', [
 ('juguetes', 'Me gusta jugar con mis juguetes.'),
 ('amigos', 'A veces otro niño quiere jugar con ellos también.'),
 ('reloj_espera', 'Podemos jugar por turnos.'),
 ('si', 'Cuando termina su turno, el juguete vuelve a mí.'),
 ('ordenar', 'Puedo guardar un juguete especial que no quiero prestar.'),
 ('feliz', 'Compartir hace que jugar sea más divertido.'),
], 'Permite guardar 1 o 2 juguetes "especiales" antes de que vengan visitas: facilita compartir el resto.'),
('amigos', 'Espero mi turno', [
 ('fila', 'A veces tengo que esperar mi turno.'),
 ('parque', 'En el tobogán, en un juego o para hablar.'),
 ('reloj_espera', 'Esperar puede ser difícil.'),
 ('respirar', 'Mientras espero, respiro o cuento hasta 10.'),
 ('si', 'Mi turno siempre llega.'),
 ('feliz', 'Esperar es justo para todos.'),
], 'Un reloj de arena visual ayuda a "ver" cuánto falta.'),
('amigos', 'Juego con otros niños', [
 ('parque', 'En el parque hay niños jugando.'),
 ('amigos', 'Puedo acercarme a un niño.'),
 ('pregunta', 'Pregunto: "¿Puedo jugar contigo?".'),
 ('si', 'Si dice que sí, jugamos juntos.'),
 ('no', 'Si dice que no, está bien. Busco otro juego.'),
 ('feliz', 'Jugar con amigos es divertido.'),
], 'Practica la frase con juego de roles en casa antes de ir al parque.'),
('amigos', 'Pido ayuda', [
 ('pregunta', 'A veces algo es difícil para mí.'),
 ('enojado', 'Me puedo sentir frustrado.'),
 ('adulto', 'Puedo buscar a un adulto.'),
 ('mano_arriba', 'Digo: "¿Me ayudas, por favor?".'),
 ('si', 'Pedir ayuda está bien. Todos lo hacemos.'),
 ('feliz', 'Con ayuda, puedo lograrlo.'),
], 'Responde siempre que pida ayuda de forma adecuada: así aprende que funciona.'),
('amigos', 'Pido perdón', [
 ('amigos', 'A veces, sin querer, hago sentir mal a alguien.'),
 ('triste', 'La otra persona puede estar triste o enojada.'),
 ('corazon', 'Puedo decir: "Perdón, no quise hacerte daño".'),
 ('pregunta', 'Puedo preguntar: "¿Estás bien?".'),
 ('abrazo', 'Si quiere, podemos darnos un abrazo.'),
 ('feliz', 'Pedir perdón ayuda a seguir siendo amigos.'),
], 'No fuerces el perdón en plena crisis. Retómalo cuando el niño esté tranquilo.'),
('amigos', 'Mi espacio y el de los demás', [
 ('yo', 'Cada persona tiene un espacio alrededor de su cuerpo.'),
 ('amigos', 'Cuando hablo, me quedo a un brazo de distancia.'),
 ('manos', 'Antes de tocar a alguien, pregunto si puedo.'),
 ('no', 'Si alguien dice "no", respeto su espacio.'),
 ('si', 'Mi cuerpo también es mío. Puedo decir "no".'),
 ('feliz', 'Así todos nos sentimos cómodos.'),
], 'Usa un aro (hula-hula) para mostrar visualmente el "espacio personal".'),
('amigos', 'Cuando un amigo está triste', [
 ('triste', 'A veces veo a un amigo triste.'),
 ('pregunta', 'Puedo preguntarle: "¿Estás bien?".'),
 ('reloj_espera', 'Escucho lo que me cuenta.'),
 ('abrazo', 'Puedo ofrecerle un abrazo o mi juguete.'),
 ('adulto', 'Si es algo grave, aviso a un adulto.'),
 ('feliz', 'Ayudar a un amigo me hace sentir bien.'),
], 'Señala emociones en cuentos y dibujos animados: "¿cómo crees que se siente?".'),
('amigos', 'Digo gracias', [
 ('regalo', 'Cuando alguien me da algo o me ayuda...'),
 ('corazon', '...digo "gracias".'),
 ('feliz', 'Puedo mirar a la persona y sonreír.'),
 ('pastel', 'También digo gracias por la comida o un regalo.'),
 ('si', 'Aunque un regalo no me guste mucho, digo gracias.'),
 ('feliz', 'Decir gracias hace felices a los demás.'),
], 'Modela el "gracias" en casa todos los días, también hacia el niño.'),
('amigos', 'Cuando otro no quiere jugar', [
 ('pelota', 'A veces quiero jugar con alguien.'),
 ('no', 'A veces esa persona no quiere jugar ahora.'),
 ('triste', 'Me puedo sentir triste. Está bien.'),
 ('reloj_espera', 'Tal vez quiera jugar en otro momento.'),
 ('amigos', 'Puedo buscar a otro amigo o jugar solo.'),
 ('feliz', 'Siempre hay algo divertido para hacer.'),
], 'Ayúdale a tener una lista de "cosas que puedo hacer solo" para estos momentos.'),

# ---------------------------------------------------------------- CASA (6)
('casa', 'Duermo en mi cama', [
 ('luna', 'Cuando es de noche, es hora de dormir.'),
 ('cepillo', 'Me pongo el pijama y me lavo los dientes.'),
 ('libro', 'Leemos un cuento juntos.'),
 ('cama_dormir', 'Me acuesto en mi cama.'),
 ('calma', 'Cierro los ojos y respiro despacio.'),
 ('adulto', 'Mamá y papá están cerca, en casa.'),
 ('sol', 'Cuando sale el sol, es un nuevo día.'),
], 'La misma rutina, en el mismo orden, cada noche, ayuda al cuerpo a prepararse para dormir.'),
('casa', 'Llega un hermanito', [
 ('bebe', 'Pronto va a llegar un bebé a mi familia.'),
 ('familia', 'Voy a ser hermano mayor.'),
 ('ruido', 'Los bebés lloran. Así nos dicen lo que necesitan.'),
 ('reloj_espera', 'Mamá y papá cuidan mucho al bebé.'),
 ('corazon', 'Mamá y papá me siguen queriendo igual.'),
 ('abrazo', 'Puedo ayudar a cuidar al bebé.'),
 ('feliz', 'Tener un hermano es muy especial.'),
], 'Reserva un tiempo exclusivo cada día con el hermano mayor, aunque sean 10 minutos.'),
('casa', 'Vienen visitas', [
 ('casa', 'Hoy vienen visitas a mi casa.'),
 ('puerta', 'Cuando lleguen, puedo saludar.'),
 ('ruido', 'Puede haber más ruido de lo normal.'),
 ('juguetes', 'Puedo mostrarles mis juguetes, si quiero.'),
 ('silla', 'Si me canso, puedo ir a mi cuarto un rato.'),
 ('puerta', 'Después las visitas se van y la casa vuelve a estar tranquila.'),
], 'Anticipa quién vendrá, cuánto tiempo y dónde podrá descansar.'),
('casa', 'Apago la tablet', [
 ('tablet', 'Me gusta usar la tablet.'),
 ('reloj_espera', 'Tengo un tiempo para usarla.'),
 ('alarma', 'Cuando suena la alarma, el tiempo terminó.'),
 ('enojado', 'Puedo sentir enojo al apagarla. Está bien.'),
 ('respirar', 'Respiro y la entrego a un adulto.'),
 ('pelota', 'Ahora puedo hacer otra cosa divertida.'),
 ('feliz', 'Mañana puedo usarla otra vez.'),
], 'Avisa 5 y 2 minutos antes del final, y ten preparada la siguiente actividad.'),
('casa', 'La hora del baño', [
 ('tina', 'Después de jugar, es hora del baño.'),
 ('jabon', 'El agua y el jabón limpian mi cuerpo.'),
 ('reloj_espera', 'Me lavo por partes: brazos, panza, piernas y pies.'),
 ('pelota', 'Puedo jugar un poquito con mis juguetes de baño.'),
 ('toalla', 'Al terminar, me seco con la toalla.'),
 ('feliz', 'Quedo limpio, fresco y listo para dormir.'),
], 'Mantén la misma temperatura del agua y avisa antes de mojar la cabeza.'),
('casa', 'Ordeno mis juguetes', [
 ('juguetes', 'Después de jugar, mis juguetes están por todos lados.'),
 ('ordenar', 'Cada juguete tiene su lugar.'),
 ('reloj_espera', 'Puedo guardar uno a la vez.'),
 ('amigos', 'Si alguien me ayuda, terminamos más rápido.'),
 ('casa', 'Mi cuarto queda ordenado.'),
 ('feliz', 'Así encuentro fácil mis juguetes la próxima vez.'),
], 'Etiqueta las cajas con fotos de lo que va dentro.'),

# ------------------------------------------------------------ SALIDAS (6)
('salidas', 'Vamos al supermercado', [
 ('carrito', 'Hoy vamos al supermercado a comprar comida.'),
 ('ruido', 'Hay mucha gente, luces y ruido.'),
 ('adulto', 'Camino cerca de mamá o papá o voy en el carrito.'),
 ('libro', 'Puedo ayudar a buscar cosas de la lista.'),
 ('no', 'No compramos todo lo que vemos.'),
 ('reloj_espera', 'Esperamos en la fila para pagar.'),
 ('feliz', 'Volvemos a casa con las compras.'),
], 'Dale una lista con fotos de 3 productos para buscar: le da una tarea y reduce la ansiedad.'),
('salidas', 'Viajo en avión', [
 ('maleta', 'Vamos a viajar en avión.'),
 ('fila', 'En el aeropuerto hacemos filas y esperamos.'),
 ('avion', 'Subimos al avión y buscamos nuestros asientos.'),
 ('silla', 'Me pongo el cinturón de seguridad.'),
 ('ruido', 'El avión hace ruido al despegar. Mis oídos pueden sentirse raros.'),
 ('auriculares', 'Puedo usar mis auriculares, comer algo o mirar un libro.'),
 ('feliz', 'Cuando el avión aterriza, ¡llegamos!'),
], 'Masticar o tomar agua al despegar alivia la presión en los oídos.'),
('salidas', 'Viajo en auto o en bus', [
 ('auto', 'Hoy vamos a viajar.'),
 ('silla', 'Me siento en mi asiento y me pongo el cinturón.'),
 ('reloj_espera', 'El viaje puede durar un rato.'),
 ('libro', 'Puedo escuchar música, mirar por la ventana o jugar.'),
 ('mano_arriba', 'Si necesito algo, le aviso a un adulto.'),
 ('feliz', 'Cuando llegamos, me bajo con cuidado.'),
], 'Una "bolsa de viaje" con juguetes que solo se usan en el auto mantiene el interés.'),
('salidas', 'Voy a una fiesta de cumpleaños', [
 ('globo', 'Me invitaron a una fiesta de cumpleaños.'),
 ('regalo', 'Llevamos un regalo para el cumpleañero.'),
 ('ruido', 'En las fiestas hay música, niños y ruido.'),
 ('pastel', 'Cantamos "Feliz cumpleaños" y comemos pastel.'),
 ('puerta', 'Si me siento abrumado, puedo descansar en un lugar tranquilo.'),
 ('feliz', 'Al irme, digo "gracias" y "adiós".'),
], 'Llega temprano, cuando hay menos gente, y acuerda una señal para irse si lo necesita.'),
('salidas', 'Vamos al parque', [
 ('parque', 'Hoy vamos al parque.'),
 ('amigos', 'Hay otros niños jugando.'),
 ('fila', 'En los juegos espero mi turno.'),
 ('adulto', 'Me quedo donde un adulto me pueda ver.'),
 ('alarma', 'Cuando es hora de irnos, me avisan antes.'),
 ('feliz', 'Me despido del parque. Podemos volver otro día.'),
], 'Usa un temporizador visible: "cuando suene, nos vamos".'),
('salidas', 'Comemos en un restaurante', [
 ('restaurante', 'Hoy comemos en un restaurante.'),
 ('silla', 'Nos sentamos en una mesa.'),
 ('reloj_espera', 'Esperamos a que traigan la comida.'),
 ('libro', 'Mientras espero, puedo dibujar o jugar en silencio.'),
 ('plato', 'Como mi comida en la mesa.'),
 ('feliz', 'Al terminar, decimos gracias y volvemos a casa.'),
], 'Lleva una actividad tranquila para la espera y elige horarios con poca gente.'),
]
