"""Las 50 historias sociales (versión narrativa): (categoría, título, [(pictograma, texto)], nota para el adulto)."""

CATS = {
 'salud': ('Salud y cuidado personal', 'hospital'),
 'colegio': ('En el colegio', 'escuela'),
 'emociones': ('Mis emociones', 'calma'),
 'amigos': ('Con los demás', 'amigos'),
 'casa': ('En casa', 'casa'),
 'salidas': ('Salidas y viajes', 'auto'),
}

H = [
# ================================================================ SALUD (7)
('salud', 'El día que fui al médico', [
 ('sol', 'Hoy por la mañana mamá me dijo: "Vamos a ir al médico para ver que estés creciendo sano".'),
 ('hospital', 'Llegamos a un edificio grande y blanco. Adentro había una sala con sillas y otros niños esperando.'),
 ('libro', 'Mientras esperábamos, miré un libro de animales. Esperar se me hizo más corto.'),
 ('doctor', 'Una voz dijo mi nombre. Entramos a un cuarto y el doctor me saludó con una sonrisa.'),
 ('termometro', 'El doctor miró mis oídos con una lucecita y escuchó mi corazón. Era frío, pero no dolía.'),
 ('respirar', 'Me sentí un poco nervioso, así que respiré despacio, como me enseñó mamá.'),
 ('feliz', 'El doctor dijo: "¡Estás muy bien!". Me sentí orgulloso de haberme quedado quieto.'),
 ('casa', 'Al salir, volvimos a casa. Ir al médico fue más fácil de lo que pensaba.'),
], 'Lee la historia varios días antes de la cita. Jugar al doctor con un peluche ayuda a practicar.'),
('salud', 'Mi visita al dentista', [
 ('diente', 'Mis dientes me ayudan a comer y a sonreír. Por eso hoy vamos a visitar al dentista.'),
 ('hospital', 'En el consultorio había una silla grande que subía y bajaba como un ascensor.'),
 ('doctor', 'La dentista me contó que iba a contar mis dientes y a ver si estaban limpios.'),
 ('sorpresa', 'Me pidió abrir la boca grande, como un león. ¡Hice el león más grande del mundo!'),
 ('ruido', 'Un aparatito hizo un ruido como de abeja. Sonaba fuerte, pero no me hizo daño.'),
 ('mano_arriba', 'Antes de empezar acordamos una señal: si necesitaba una pausa, levantaba la mano. La usé una vez y ella paró.'),
 ('feliz', 'Al final me miré en un espejo. Mis dientes brillaban y la dentista me felicitó.'),
], 'Acordar una señal para pausar da sensación de control. Pídele al dentista que la respete.'),
('salud', 'El corte de pelo', [
 ('tijeras_pelo', 'Mi pelo había crecido tanto que ya me tapaba los ojos. Papá dijo que era hora de cortarlo.'),
 ('silla', 'En la peluquería me senté en una silla alta y me pusieron una capa para que el pelo no me picara.'),
 ('calma', 'Papá me recordó que cortar el pelo no duele, porque el pelo no siente nada.'),
 ('ruido', 'La peluquera usó una maquinita que zumbaba y hacía cosquillas en mi cuello.'),
 ('auriculares', 'Me puse mis auriculares y escuché mi canción favorita mientras contaba hasta diez.'),
 ('feliz', 'Cuando terminó, me miré al espejo. ¡Ahora podía ver todo y me veía muy bien!'),
 ('abrazo', 'Papá me dio un abrazo y fuimos a casa a enseñarle mi pelo nuevo a mamá.'),
], 'Lleva su juguete o música favorita. Si es posible, corta un poquito en casa antes para acostumbrarlo.'),
('salud', 'El día de la vacuna', [
 ('jeringa', 'Mamá me explicó que hoy me tocaba una vacuna. Las vacunas son como un escudo que protege mi cuerpo.'),
 ('hospital', 'Fuimos al centro de salud. Una enfermera amable me saludó y me preguntó mi nombre.'),
 ('nervioso', 'Sentí mariposas en la panza. Mamá me dijo que estaba bien sentirme nervioso.'),
 ('abrazo', 'Me senté en las piernas de mamá y ella me abrazó fuerte.'),
 ('respirar', 'La enfermera me dijo: "Sopla como si apagaras velas". Soplé y sentí un pinchazo cortito.'),
 ('curita', 'En un momento terminó. Me pusieron una curita de colores en el brazo.'),
 ('feliz', 'Fui muy valiente. Ahora mi cuerpo tiene un escudo nuevo.'),
], 'Evita decir "no duele". Es mejor anticipar con honestidad: "vas a sentir un pinchazo corto".'),
('salud', 'Mis uñas y la tijerita', [
 ('manos', 'Una noche, después del baño, vi que mis uñas estaban largas y tenían tierra debajo.'),
 ('unas', 'Mamá sacó la tijerita especial para uñas y me dijo: "Vamos a dejarlas cortitas y limpias".'),
 ('pregunta', 'Le pregunté si iba a doler. Ella me explicó que las uñas no sienten, como el pelo.'),
 ('reloj_espera', 'Cortamos una uña a la vez y contamos los dedos juntos: uno, dos, tres...'),
 ('respirar', 'En el dedo gordo me dio cosquillas. Pedí una pausa, respiré y seguimos.'),
 ('si', '¡Diez dedos listos! Mis manos quedaron limpias y suaves.'),
], 'Hazlo después del baño, cuando las uñas están más blandas, y cuenten juntos en voz alta.'),
('salud', 'Cuando estuve enfermo', [
 ('termometro', 'Un día me desperté con calor y me dolía la garganta. Mamá me tomó la temperatura.'),
 ('cama_dormir', 'Ese día no fui al colegio. Me quedé en casa descansando en mi cama.'),
 ('doctor', 'El médico dijo que necesitaba tomar una medicina para curarme.'),
 ('medicina', 'La medicina tenía un sabor raro. La tomé rápido y después bebí un poco de agua.'),
 ('adulto', 'Mamá me explicó que solo tomo medicinas que me da un adulto.'),
 ('libro', 'Mientras me recuperaba, leímos cuentos y vimos una película juntos.'),
 ('feliz', 'Después de unos días me sentí mucho mejor y volví a jugar.'),
], 'Refuerza la regla de seguridad: los medicamentos solo los da un adulto.'),
('salud', 'El agua en mi cabeza', [
 ('tina', 'Esta noche, en el baño, mamá me dijo que íbamos a lavar mi pelo.'),
 ('miedo', 'No me gusta cuando el agua cae en mi cara. Me da miedo que entre en mis ojos.'),
 ('toalla', 'Mamá me dio una toallita seca para taparme los ojos. ¡Era mi escudo!'),
 ('jabon', 'El champú hizo mucha espuma. Me puse un sombrero de espuma y nos reímos.'),
 ('reloj_espera', 'Para enjuagar, incliné la cabeza hacia atrás y contamos hasta diez juntos.'),
 ('feliz', 'Cuando terminamos, mi pelo olía rico. Esta vez no me cayó agua en los ojos.'),
], 'Una visera de baño o inclinar la cabeza hacia atrás ayuda mucho a los niños que no toleran el agua en la cara.'),

# ============================================================= COLEGIO (11)
('colegio', 'Mi primer día de clases', [
 ('mochila', 'Hoy es un día especial: es mi primer día en el colegio. Mi mochila nueva está lista desde anoche.'),
 ('escuela', 'Cuando llegamos, vi un edificio grande con muchos niños y un patio enorme.'),
 ('nervioso', 'Mi corazón latía rápido. Es normal sentirse nervioso cuando todo es nuevo.'),
 ('maestra', 'En la puerta me esperaba mi maestra. Me dijo su nombre y me mostró dónde colgar mi mochila.'),
 ('amigos', 'En el salón, un niño se sentó a mi lado y me prestó un crayón. Dibujamos juntos.'),
 ('parque', 'En el recreo jugamos en el patio. ¡Había un tobogán!'),
 ('reloj_espera', 'Al final del día, papá llegó a buscarme, como me había prometido.'),
 ('feliz', 'Le conté todo lo que hice. Mañana quiero volver.'),
], 'Si es posible, visiten el colegio antes y tomen fotos del salón y de la maestra para pegarlas en la historia.'),
('colegio', 'Mamá siempre vuelve', [
 ('adulto', 'Cada mañana, mamá me lleva al colegio de la mano.'),
 ('abrazo', 'En la puerta nos damos un abrazo y un beso. Ella me dice: "Nos vemos a la salida".'),
 ('triste', 'Cuando la veo irse, a veces me pongo triste y me dan ganas de llorar. Está bien sentirme así.'),
 ('maestra', 'Mi maestra me toma de la mano y me ayuda a entrar al salón.'),
 ('pelota', 'Cuando empiezo a jugar y a pintar, la tristeza se va haciendo pequeña.'),
 ('reloj_espera', 'Mientras estoy en el colegio, mamá hace sus cosas, y piensa en mí.'),
 ('feliz', 'Cuando suena el timbre de salida, ahí está mamá esperándome. Mamá siempre vuelve.'),
], 'Despídete siempre, de forma breve y tranquila. Irse a escondidas aumenta la ansiedad.'),
('colegio', 'Tengo algo que decir', [
 ('maestra', 'Hoy la maestra nos estaba contando un cuento sobre dinosaurios.'),
 ('pregunta', 'De pronto se me ocurrió una pregunta: ¿los dinosaurios tenían dientes grandes?'),
 ('no', 'Tenía muchas ganas de gritarla, pero si todos hablamos a la vez, nadie se entiende.'),
 ('mano_arriba', 'Entonces levanté la mano bien alto y esperé en silencio.'),
 ('reloj_espera', 'La maestra terminó de leer la página. Esperar me costó un poquito.'),
 ('si', 'Luego dijo mi nombre. Hice mi pregunta y la maestra me respondió.'),
 ('feliz', 'Me sentí escuchado. Levantar la mano funciona.'),
], 'Practiquen en casa durante la cena: quien quiere hablar, levanta la mano.'),
('colegio', 'La fila del recreo', [
 ('alarma', 'Sonó el timbre y la maestra dijo: "Hagamos una fila para salir al patio".'),
 ('fila', 'Todos los niños se pusieron uno detrás de otro. Yo quería ser el primero.'),
 ('triste', 'Pero ya había otros adelante. Me sentí un poco molesto.'),
 ('calma', 'Respiré y me puse detrás de mi compañero, dejando un espacio para no empujarlo.'),
 ('puerta', 'Caminamos despacio por el pasillo, como un tren.'),
 ('parque', 'Llegamos todos juntos y seguros al patio.'),
 ('feliz', 'La maestra dijo que hicimos una fila perfecta. Mañana tal vez me toque ser el primero.'),
], 'Marcar en casa un lugar con cinta en el piso ayuda a entender la distancia en la fila.'),
('colegio', 'Un recreo diferente', [
 ('alarma', 'Cuando sonó el timbre del recreo, salí al patio con mi lonchera.'),
 ('lonchera', 'Primero me senté a comer mi fruta. Tenía mucha hambre.'),
 ('amigos', 'Vi a unos niños jugando a la pelota. Me dieron ganas de jugar con ellos.'),
 ('pregunta', 'Me acerqué y pregunté: "¿Puedo jugar con ustedes?".'),
 ('si', 'Uno de ellos dijo: "¡Sí! Tú estás en mi equipo". ¡Qué alegría!'),
 ('ruido', 'Después de un rato había mucho ruido, así que me senté a descansar en un rincón tranquilo.'),
 ('alarma', 'Cuando volvió a sonar el timbre, regresé al salón con energía.'),
], 'Estar solo un rato en el recreo también es válido si el niño lo necesita para regularse.'),
('colegio', 'La alarma de práctica', [
 ('maestra', 'Esta mañana la maestra nos contó que haríamos una práctica de sismo.'),
 ('alarma', 'De pronto sonó una alarma muy fuerte. Me tapé los oídos.'),
 ('miedo', 'Al principio me asusté, pero recordé que solo era una práctica.'),
 ('maestra', 'La maestra habló con voz tranquila: "Síganme, caminando y sin correr".'),
 ('fila', 'Salimos en fila hasta el patio, donde nos esperaban todos los demás salones.'),
 ('reloj_espera', 'Esperamos juntos hasta que la alarma se apagó.'),
 ('feliz', 'La directora nos felicitó. Ahora sé qué hacer si un día pasa de verdad.'),
], 'Si la alarma le molesta mucho, pide al colegio que te avise de la fecha para llevar auriculares.'),
('colegio', 'El castillo del equipo', [
 ('maestra', 'Hoy la maestra nos dio una misión: construir un castillo de papel en grupos.'),
 ('amigos', 'Me tocó con Sofía y con Mateo. Al principio no sabía qué decir.'),
 ('pregunta', 'Sofía quería torres altas y Mateo quería un puente. Yo quería una bandera.'),
 ('reloj_espera', 'Nos turnamos para hablar y escuchamos las ideas de todos.'),
 ('si', 'Decidimos hacer todo: torres, un puente... ¡y mi bandera arriba!'),
 ('calma', 'Una vez no usaron mi idea, y respiré. Pensé que habría otras oportunidades.'),
 ('feliz', 'Nuestro castillo quedó genial. Trabajar en equipo fue divertido.'),
], 'Darle un rol concreto (el que corta, el que pega) facilita que participe en el grupo.'),
('colegio', '¡Necesito ir al baño!', [
 ('escuela', 'Estábamos en medio de la clase de matemáticas.'),
 ('inodoro', 'De repente sentí que necesitaba ir al baño.'),
 ('mano_arriba', 'No me levanté corriendo. Levanté la mano y esperé que la maestra me viera.'),
 ('pregunta', 'Cuando me miró, le dije: "Maestra, ¿puedo ir al baño, por favor?".'),
 ('si', 'Ella dijo que sí. Fui al baño y, al terminar, me lavé bien las manos.'),
 ('escuela', 'Volví al salón caminando y me senté en mi lugar.'),
 ('feliz', 'Pedir permiso fue fácil. La maestra siempre me deja ir cuando lo necesito.'),
], 'Una tarjeta de "baño" para mostrar a la maestra ayuda a los niños con poco lenguaje.'),
('colegio', 'Hoy vino otra maestra', [
 ('escuela', 'Hoy entré al salón como todos los días, pero algo era distinto.'),
 ('maestra', 'Mi maestra no estaba. En su lugar había otra señora que no conocía.'),
 ('sorpresa', 'Me sentí raro y confundido. Me gusta que las cosas sean como siempre.'),
 ('adulto', 'La nueva maestra nos explicó: "Su maestra está enferma, hoy yo los voy a cuidar".'),
 ('libro', 'Hicimos las mismas cosas de siempre: leímos, pintamos y salimos al recreo.'),
 ('calma', 'Poco a poco me fui sintiendo más tranquilo.'),
 ('feliz', 'Al día siguiente, mi maestra volvió. ¡Qué bueno verla otra vez!'),
], 'Pide al colegio que avise de los cambios con anticipación: lo anticipado se vive con menos angustia.'),
('colegio', 'La hora de la lonchera', [
 ('lonchera', 'Anoche preparé mi lonchera con papá. Elegí manzana, galletas y agua.'),
 ('alarma', 'En el colegio sonó el timbre de la merienda. ¡Por fin!'),
 ('jabon', 'Antes de comer, fui a lavarme las manos con jabón.'),
 ('silla', 'Me senté en mi lugar, al lado de mi amiga Valentina.'),
 ('plato', 'Abrí mi lonchera y comí despacio, masticando bien. Valentina me mostró su sándwich.'),
 ('ordenar', 'Cuando terminé, guardé todo en mi lonchera y la cerré.'),
 ('feliz', 'Con la panza llena, tenía energía para seguir aprendiendo.'),
], 'Preparar la lonchera juntos el día anterior le da anticipación y sensación de control.'),
('colegio', 'La tarea de los números', [
 ('libro', 'Hoy traje del colegio una hoja de tarea con números para completar.'),
 ('silla', 'Después de merendar, me senté en mi lugar de tareas, con mis lápices listos.'),
 ('lapiz', 'Empecé por el primer ejercicio. Iba muy bien.'),
 ('enojado', 'Pero en el tercero me trabé y me dieron ganas de tirar el lápiz.'),
 ('reloj_espera', 'En vez de eso, tomé una pausa corta, tomé agua y estiré los brazos.'),
 ('pregunta', 'Después le pedí ayuda a mamá. Ella me explicó con unos frijolitos para contar.'),
 ('feliz', '¡Terminé toda la hoja! Guardé mi tarea en la mochila, orgulloso.'),
], 'Divide la tarea en partes, usa un temporizador y celebra el esfuerzo, no solo el resultado.'),

# ============================================================ EMOCIONES (10)
('emociones', 'El volcán que llevo dentro', [
 ('bloques', 'Estaba construyendo la torre más alta del mundo con mis bloques.'),
 ('sorpresa', 'De pronto, mi hermanito pasó corriendo y ¡pum!, la torre se cayó.'),
 ('enojado', 'Sentí un volcán dentro de mí: la cara caliente, los puños apretados y ganas de gritar.'),
 ('no', 'Tuve ganas de empujarlo, pero empujar puede lastimar.'),
 ('respirar', 'Entonces respiré como me enseñaron: inflé la panza como un globo y solté el aire despacio.'),
 ('reloj_espera', 'Conté hasta diez. El volcán se fue calmando.'),
 ('adulto', 'Fui a decirle a papá: "Estoy enojado porque tiraron mi torre". Él me escuchó.'),
 ('feliz', 'Después, mi hermano y yo construimos una torre nueva, ¡más alta que la anterior!'),
], 'Practica la respiración en momentos tranquilos, no solo durante la crisis.'),
('emociones', 'El día gris', [
 ('triste', 'Hoy mi mejor amigo se mudó a otra ciudad. Me sentí muy triste.'),
 ('pregunta', 'Mi cuerpo se sentía pesado y no tenía ganas de jugar.'),
 ('si', 'Lloré un poco. Mamá me dijo que llorar está bien, que ayuda a sacar la tristeza.'),
 ('abrazo', 'Le pedí un abrazo y nos quedamos así un ratito.'),
 ('lapiz', 'Después dibujé a mi amigo y a mí jugando a la pelota.'),
 ('adulto', 'Mamá dijo que podemos enviarle el dibujo y llamarlo por teléfono.'),
 ('feliz', 'Seguía extrañándolo, pero ya no me sentía tan gris.'),
], 'Valida la emoción ("veo que estás triste") antes de intentar solucionarla.'),
('emociones', 'La tormenta de la noche', [
 ('luna', 'Una noche, mientras dormía, me despertó un ruido muy fuerte.'),
 ('ruido', '¡Era un trueno! Afuera había una tormenta con mucha lluvia.'),
 ('miedo', 'Me dio mucho miedo. Me tapé con la manta hasta la cabeza.'),
 ('adulto', 'Llamé a papá y él vino a mi cuarto. Le dije: "Tengo miedo".'),
 ('abrazo', 'Papá me abrazó y me explicó que los truenos hacen ruido, pero no pueden entrar a casa.'),
 ('respirar', 'Contamos juntos el tiempo entre un trueno y otro. Abracé fuerte a mi peluche.'),
 ('cama_dormir', 'Poco a poco la tormenta se alejó y me volví a dormir.'),
 ('sol', 'A la mañana siguiente salió el sol. Fui valiente.'),
], 'Ponerle nombre al miedo lo hace más manejable. Nunca te burles de un miedo, aunque parezca pequeño.'),
('emociones', 'El juego que perdí', [
 ('pelota', 'Esta tarde jugué con mi prima a un juego de mesa con dados.'),
 ('feliz', 'Al principio yo iba ganando. ¡Estaba muy contento!'),
 ('sorpresa', 'Pero mi prima sacó un seis y llegó primero a la meta.'),
 ('enojado', 'Sentí ganas de tirar las fichas. Perder no me gusta nada.'),
 ('respirar', 'Respiré profundo y recordé que en los juegos a veces se gana y a veces se pierde.'),
 ('amigos', 'Le dije a mi prima: "Bien jugado". Ella sonrió.'),
 ('si', 'Jugamos otra vez y ese juego lo gané yo.'),
 ('feliz', 'Lo más divertido no era ganar: era jugar juntos.'),
], 'Juega en casa juegos cortos donde pierdas a propósito y muéstrale cómo reaccionar.'),
('emociones', 'Cuando cambió el plan', [
 ('parque', 'Toda la semana esperé el sábado, porque íbamos a ir al parque.'),
 ('sol', 'El sábado me desperté temprano, listo para salir.'),
 ('sorpresa', 'Pero al mirar por la ventana, ¡estaba lloviendo muchísimo!'),
 ('enojado', 'Mamá me dijo que no podíamos ir. Me enojé mucho, porque yo tenía otro plan.'),
 ('respirar', 'Me senté en el sofá y respiré. Mamá me mostró un plan nuevo.'),
 ('casa', 'Armamos un campamento con mantas en la sala e hicimos un picnic en el suelo.'),
 ('feliz', 'Fue un día distinto, pero también fue divertido. El parque nos espera otro día.'),
], 'Usa una tarjeta de "cambio" o "sorpresa" en su agenda visual para practicar los imprevistos.'),
('emociones', 'Demasiado ruido', [
 ('globo', 'Fuimos a la fiesta de mi tía. Había música, globos y mucha gente.'),
 ('ruido', 'Al rato, la música sonaba cada vez más fuerte y todos hablaban a la vez.'),
 ('nervioso', 'Me empezaron a molestar los oídos y sentí ganas de salir corriendo.'),
 ('adulto', 'Busqué a mamá y le dije: "Hay demasiado ruido".'),
 ('auriculares', 'Mamá sacó mis auriculares de la bolsa y me los puse.'),
 ('puerta', 'Después salimos un ratito al jardín, donde había silencio.'),
 ('calma', 'Cuando me sentí mejor, volví a la fiesta y comí pastel.'),
], 'Lleva siempre auriculares con cancelación de ruido a lugares concurridos.'),
('emociones', 'Mariposas en la panza', [
 ('escuela', 'Mañana tengo que cantar con mi clase en el acto del colegio.'),
 ('nervioso', 'Cuando lo pienso, siento mariposas en la panza y me sudan las manos.'),
 ('pregunta', 'Le pregunté a papá si eso era normal. Me dijo que a él también le pasa cuando hace algo nuevo.'),
 ('libro', 'Practicamos la canción juntos en la sala, varias veces.'),
 ('respirar', 'También practicamos la respiración del globo: inflar, aguantar y soltar.'),
 ('amigos', 'El día del acto, miré a mis compañeros y canté con ellos.'),
 ('feliz', 'Las mariposas se fueron volando. ¡Lo logré!'),
], 'Anticipar con esta historia y practicar en casa reduce los nervios ante situaciones nuevas.'),
('emociones', 'Mi rincón tranquilo', [
 ('escuela', 'Hoy fue un día largo: clases, ruido, actividades y mucha gente.'),
 ('nervioso', 'En la tarde me sentía cansado, como un globo a punto de explotar.'),
 ('mano_arriba', 'Recordé que puedo pedir un descanso. Le mostré mi tarjeta a la maestra.'),
 ('silla', 'Ella me acompañó al rincón tranquilo, donde hay un cojín y unos libros.'),
 ('reloj_espera', 'Me quedé ahí unos minutos, respirando y mirando un libro.'),
 ('calma', 'Poco a poco mi cuerpo se fue calmando.'),
 ('feliz', 'Cuando me sentí mejor, volví a la clase con mis compañeros.'),
], 'Crea una tarjeta de "descanso" y respeta su uso: así aprende a pedirlo en lugar de explotar.'),
('emociones', 'El dibujo que salió mal', [
 ('lapiz', 'Quería dibujar un caballo para regalárselo a la abuela.'),
 ('sorpresa', 'Pero las patas me salieron muy largas, y parecía una jirafa.'),
 ('triste', 'Me sentí frustrado y quise romper el papel.'),
 ('adulto', 'La abuela me dijo: "Todos nos equivocamos. Así es como se aprende".'),
 ('respirar', 'Respiré y lo intenté otra vez, más despacio.'),
 ('si', 'El segundo caballo me salió mejor. ¡Y la jirafa también me gustó!'),
 ('feliz', 'Le regalé los dos dibujos a la abuela. Los pegó en su refrigerador.'),
], 'Comparte tus propios errores en voz alta: "uy, me equivoqué, lo hago otra vez".'),
('emociones', 'Cuando me dijeron que no', [
 ('carrito', 'Estábamos en el supermercado cuando vi un auto de juguete rojo, brillante.'),
 ('pregunta', 'Le pregunté a mamá: "¿Me lo compras?".'),
 ('no', 'Mamá dijo: "Hoy no, solo vinimos a comprar comida".'),
 ('enojado', 'Me enojé y me dieron ganas de tirarme al suelo.'),
 ('respirar', 'Respiré profundo y miré el auto una última vez.'),
 ('adulto', 'Mamá me dijo que podía ponerlo en mi lista de cumpleaños. Le saqué una foto.'),
 ('feliz', 'Después la ayudé a elegir las frutas. ¡Elegí las mejores manzanas!'),
], 'Ofrece alternativas posibles después del "no": elegir le da sensación de control.'),

# ============================================================== AMIGOS (10)
('amigos', 'Hola, vecino', [
 ('casa', 'Esta mañana, al salir de casa, vi a mi vecino, don Pedro, regando sus plantas.'),
 ('manos', 'Moví la mano y le dije: "¡Hola, don Pedro!".'),
 ('feliz', 'Él sonrió y me dijo: "¡Hola! ¿Vas al colegio?".'),
 ('si', 'Le respondí que sí y le conté que hoy tenía clase de música.'),
 ('puerta', 'Cuando nos fuimos, le dije: "¡Adiós!", y él me saludó con la mano.'),
 ('adulto', 'Mamá me dijo que saludar hace sentir bien a las personas.'),
 ('feliz', 'Y es verdad: yo también me sentí bien.'),
], 'Si no le gustan los abrazos o los besos, ofrécele alternativas: chocar la mano o saludar de lejos.'),
('amigos', 'Mi auto favorito', [
 ('juguetes', 'Mi primo vino a jugar a casa. Saqué mis juguetes al patio.'),
 ('sorpresa', 'Él tomó mi auto azul, ¡mi favorito!'),
 ('enojado', 'Sentí ganas de quitárselo de las manos.'),
 ('reloj_espera', 'Mamá nos ayudó: "Él juega un rato y luego es tu turno".'),
 ('bloques', 'Mientras esperaba, construí una rampa con bloques.'),
 ('si', 'Cuando llegó mi turno, ¡el auto bajó volando por la rampa!'),
 ('amigos', 'Después jugamos juntos: él empujaba y yo armaba las rampas.'),
 ('feliz', 'Compartir hizo que el juego fuera el doble de divertido.'),
], 'Permite guardar uno o dos juguetes "especiales" antes de que vengan visitas: facilita compartir el resto.'),
('amigos', 'El tobogán', [
 ('parque', 'En el parque, corrí directo al tobogán más alto.'),
 ('fila', 'Pero había varios niños esperando en la escalera.'),
 ('enojado', 'Yo quería subir ya. Esperar me pone impaciente.'),
 ('respirar', 'Me puse al final de la fila y conté los niños que había delante: uno, dos, tres.'),
 ('reloj_espera', 'Cada vez que uno bajaba, yo avanzaba un escalón.'),
 ('si', '¡Por fin llegó mi turno! Bajé rapidísimo.'),
 ('feliz', 'Esperar es justo para todos. Y mi turno siempre llega.'),
], 'Un reloj de arena o un temporizador visual ayuda a "ver" cuánto falta.'),
('amigos', 'Un amigo nuevo en el parque', [
 ('parque', 'En el parque vi a un niño haciendo un castillo de arena.'),
 ('nervioso', 'Quería jugar con él, pero me daba vergüenza acercarme.'),
 ('respirar', 'Respiré, caminé hasta allí y le pregunté: "¿Puedo jugar contigo?".'),
 ('si', 'Él dijo: "¡Sí! Necesito alguien que traiga agua".'),
 ('amigos', 'Llevé agua en mi baldecito y juntos hicimos un foso alrededor del castillo.'),
 ('pregunta', 'Le pregunté su nombre. Se llamaba Tomás.'),
 ('feliz', 'Antes de irnos, Tomás me dijo: "¿Jugamos mañana?". ¡Tengo un amigo nuevo!'),
], 'Practica la frase "¿puedo jugar contigo?" con juego de roles antes de ir al parque.'),
('amigos', 'La botella que no se abría', [
 ('vaso', 'Tenía mucha sed y quería tomar mi jugo.'),
 ('enojado', 'Intenté abrir la botella, pero la tapa estaba muy dura. Me empecé a frustrar.'),
 ('no', 'Me dieron ganas de tirarla al suelo, pero así no se iba a abrir.'),
 ('adulto', 'Entonces fui con mi abuelo y le dije: "¿Me ayudas, por favor?".'),
 ('si', 'Mi abuelo la abrió y me enseñó un truco: girar fuerte con toda la mano.'),
 ('feliz', 'Tomé mi jugo. Pedir ayuda fue mucho mejor que enojarme.'),
], 'Responde siempre cuando pida ayuda de forma adecuada: así aprende que funciona.'),
('amigos', 'Sin querer', [
 ('pelota', 'En el recreo estábamos jugando a la pelota.'),
 ('sorpresa', 'Pateé muy fuerte y, sin querer, la pelota le dio a Lucía en el brazo.'),
 ('triste', 'Lucía empezó a llorar. Me sentí mal, porque yo no quería lastimarla.'),
 ('corazon', 'Me acerqué y le dije: "Perdón, Lucía, fue sin querer".'),
 ('pregunta', 'Le pregunté: "¿Estás bien? ¿Quieres que llame a la maestra?".'),
 ('abrazo', 'Lucía dejó de llorar y me dijo que ya estaba mejor.'),
 ('feliz', 'Seguimos jugando, esta vez con más cuidado.'),
], 'No fuerces el perdón en plena crisis: retómalo cuando el niño esté tranquilo.'),
('amigos', 'Mi burbuja', [
 ('yo', 'Mi maestra nos contó que cada persona tiene una burbuja invisible alrededor de su cuerpo.'),
 ('amigos', 'Cuando hablo con alguien, me quedo a un brazo de distancia, para no reventar su burbuja.'),
 ('manos', 'Si quiero abrazar o tocar a alguien, primero le pregunto: "¿Puedo?".'),
 ('no', 'Hoy le pregunté a mi amigo si podía abrazarlo y me dijo que no. Respeté su burbuja.'),
 ('si', 'Él prefirió chocar las manos. ¡Chocamos los cinco!'),
 ('yo', 'Mi cuerpo también tiene su burbuja. Yo también puedo decir "no".'),
 ('feliz', 'Cuando cuidamos las burbujas, todos nos sentimos cómodos.'),
], 'Usa un aro (hula-hula) alrededor del niño para mostrar visualmente el espacio personal.'),
('amigos', 'Mi amiga estaba triste', [
 ('escuela', 'Hoy, al llegar al salón, vi a mi amiga Camila sentada sola.'),
 ('triste', 'Tenía la cara triste y miraba al suelo.'),
 ('pregunta', 'Me acerqué y le pregunté: "¿Estás bien?".'),
 ('reloj_espera', 'Ella me contó que se le había perdido su lápiz favorito. La escuché.'),
 ('abrazo', 'Le dije: "Si quieres, te presto uno de los míos". Y le di mi lápiz de estrellas.'),
 ('feliz', 'Camila sonrió y me dio las gracias.'),
 ('corazon', 'Ayudar a una amiga me hizo sentir muy bien por dentro.'),
], 'Señala emociones en cuentos y dibujos animados: "¿cómo crees que se siente?".'),
('amigos', 'El regalo de la abuela', [
 ('regalo', 'Por mi cumpleaños, la abuela me trajo un regalo envuelto en papel brillante.'),
 ('sorpresa', 'Lo abrí con emoción... ¡eran unos calcetines!'),
 ('pregunta', 'Yo esperaba un juguete, y me sentí un poco desilusionado.'),
 ('corazon', 'Pero pensé que la abuela los había elegido con cariño para mí.'),
 ('feliz', 'La miré, sonreí y le dije: "Gracias, abuela".'),
 ('abrazo', 'Ella me dio un abrazo enorme. Se veía muy feliz.'),
 ('si', 'Decir "gracias" hace sentir bien a quien nos da algo.'),
], 'Modela el "gracias" todos los días en casa, también hacia el niño.'),
('amigos', 'Ahora no quiero jugar', [
 ('pelota', 'Hoy en el recreo quería jugar a la pelota con Martín.'),
 ('pregunta', 'Le pregunté: "¿Jugamos?".'),
 ('no', 'Martín me dijo: "Ahora no, estoy leyendo mi libro".'),
 ('triste', 'Me sentí un poco triste. Yo tenía muchas ganas de jugar con él.'),
 ('reloj_espera', 'Pensé que tal vez él quería jugar en otro momento.'),
 ('amigos', 'Entonces fui a saltar la cuerda con otras niñas.'),
 ('feliz', 'Al día siguiente, Martín me buscó para jugar a la pelota.'),
], 'Ayúdale a tener una lista de "cosas que puedo hacer solo" para estos momentos.'),

# ================================================================ CASA (6)
('casa', 'Buenas noches, mi cama', [
 ('luna', 'Cuando afuera se pone oscuro, en casa empieza la hora de dormir.'),
 ('tina', 'Primero me baño, después me pongo mi pijama de estrellas.'),
 ('cepillo', 'Me cepillo los dientes frente al espejo, arriba y abajo.'),
 ('libro', 'Luego, papá me lee un cuento en mi cama. Hoy fue uno de piratas.'),
 ('abrazo', 'Papá me da un beso, apaga la luz grande y deja encendida mi lucecita.'),
 ('calma', 'Cierro los ojos y respiro despacio. Sé que mamá y papá están cerca.'),
 ('cama_dormir', 'Mi cuerpo descansa toda la noche en mi cama.'),
 ('sol', 'Cuando sale el sol, me despierto listo para un nuevo día.'),
], 'La misma rutina, en el mismo orden, cada noche, ayuda al cuerpo a prepararse para dormir.'),
('casa', 'Llegó mi hermanita', [
 ('familia', 'Durante meses, la panza de mamá creció y creció. Adentro estaba mi hermanita.'),
 ('bebe', 'Un día, mamá y papá volvieron del hospital con ella. Era muy pequeñita.'),
 ('ruido', 'Al principio lloraba mucho, sobre todo de noche. Así nos dice que tiene hambre o sueño.'),
 ('reloj_espera', 'Mamá pasaba mucho tiempo cuidándola, y a veces yo tenía que esperar.'),
 ('triste', 'Un día le pregunté a mamá si todavía me quería.'),
 ('corazon', 'Ella me abrazó y me dijo: "Te quiero igual que siempre. El amor no se divide, se multiplica".'),
 ('abrazo', 'Ahora la ayudo a cuidarla: le canto canciones y le alcanzo los pañales.'),
 ('feliz', 'Ser hermano mayor es muy especial.'),
], 'Reserva un tiempo exclusivo cada día con el hermano mayor, aunque sean 10 minutos.'),
('casa', 'Visitas en casa', [
 ('casa', 'Hoy vinieron mis tíos y mis primos a almorzar a casa.'),
 ('puerta', 'Cuando tocaron el timbre, abrimos la puerta y los saludé con la mano.'),
 ('ruido', 'Pronto la casa se llenó de voces, risas y ruido.'),
 ('juguetes', 'Les mostré a mis primos mis bloques y jugamos un rato.'),
 ('nervioso', 'Después de un tiempo me sentí cansado de tanto ruido.'),
 ('silla', 'Le avisé a mamá y fui a mi cuarto a descansar un ratito, como habíamos acordado.'),
 ('puerta', 'En la tarde, las visitas se despidieron y la casa volvió a estar tranquila.'),
], 'Anticipa quién vendrá, cuánto tiempo y dónde podrá descansar si se agobia.'),
('casa', 'El tiempo de la tablet', [
 ('tablet', 'Después de la merienda, me toca mi tiempo de tablet. Hoy elegí un juego de dinosaurios.'),
 ('alarma', 'Papá puso una alarma. Cuando faltaban cinco minutos, me avisó.'),
 ('reloj_espera', 'Aproveché para terminar mi nivel.'),
 ('alarma', 'Luego sonó la alarma: el tiempo había terminado.'),
 ('enojado', 'Quería seguir jugando y me enojé un poquito.'),
 ('respirar', 'Respiré, apagué la tablet y se la entregué a papá.'),
 ('pelota', 'Papá me dijo: "¿Salimos a jugar a la pelota?". ¡Fue muy divertido!'),
 ('feliz', 'Mañana puedo volver a usar la tablet.'),
], 'Avisa 5 y 2 minutos antes del final y ten preparada la siguiente actividad.'),
('casa', 'El barco de la bañera', [
 ('parque', 'Hoy jugué en el parque y volví con las manos y las rodillas llenas de tierra.'),
 ('tina', 'Mamá llenó la bañera con agua tibia. ¡Hora del baño!'),
 ('pelota', 'Me llevé mi barquito de juguete para que me acompañara.'),
 ('jabon', 'Con la esponja y el jabón, lavé mis brazos, mi panza, mis piernas y mis pies.'),
 ('miedo', 'Antes de mojar mi cabeza, mamá me avisó, y yo cerré los ojos.'),
 ('toalla', 'Al salir, me envolví en la toalla como un burrito.'),
 ('feliz', 'Quedé limpio, fresquito y listo para dormir.'),
], 'Mantén la temperatura del agua y avisa siempre antes de mojarle la cabeza.'),
('casa', 'La misión de ordenar', [
 ('juguetes', 'Después de jugar toda la tarde, mi cuarto parecía un campo de batalla.'),
 ('pregunta', 'Mamá me dijo: "Tengo una misión para ti: devolver cada juguete a su casa".'),
 ('ordenar', 'Las piezas de bloques van en la caja azul y los autos en el cajón.'),
 ('reloj_espera', 'Puse música y guardé un juguete a la vez, antes de que terminara la canción.'),
 ('amigos', 'Mi hermano me ayudó con los peluches. Terminamos más rápido.'),
 ('casa', '¡Misión cumplida! Mi cuarto quedó ordenado.'),
 ('feliz', 'Mañana encontraré mis juguetes muy fácil.'),
], 'Etiqueta las cajas con fotos de lo que va dentro: así puede ordenar sin ayuda.'),

# ============================================================= SALIDAS (6)
('salidas', 'Las compras del sábado', [
 ('carrito', 'Los sábados vamos al supermercado. Hoy papá me dio una misión: buscar tres cosas de la lista.'),
 ('ruido', 'En el supermercado había luces, música y muchas personas con carritos.'),
 ('adulto', 'Caminé al lado de papá, empujando el carrito con él.'),
 ('libro', 'Encontré la leche, los plátanos y el pan. ¡Misión cumplida!'),
 ('no', 'Pasamos por los dulces y quise unos chocolates, pero hoy no estaban en la lista.'),
 ('reloj_espera', 'En la caja hicimos fila para pagar. Ayudé a poner las cosas en la banda.'),
 ('feliz', 'Volvimos a casa cargando las bolsas. Fui un gran ayudante.'),
], 'Dale una lista con fotos de tres productos para buscar: le da una tarea y reduce la ansiedad.'),
('salidas', 'Mi primer viaje en avión', [
 ('maleta', 'Vamos a visitar a la abuela, que vive lejos. ¡Vamos a viajar en avión!'),
 ('fila', 'En el aeropuerto hicimos varias filas y entregamos nuestras maletas.'),
 ('avion', 'Por la ventana vi aviones gigantes. Luego subimos al nuestro y buscamos nuestros asientos.'),
 ('silla', 'Me puse el cinturón de seguridad, igual que en el auto.'),
 ('ruido', 'Cuando el avión despegó, los motores rugieron y mis oídos se sintieron raros.'),
 ('auriculares', 'Mastiqué un caramelo, me puse mis auriculares y miré las nubes desde arriba.'),
 ('abrazo', 'Cuando aterrizamos, la abuela nos esperaba con los brazos abiertos.'),
], 'Masticar o tomar agua durante el despegue y el aterrizaje alivia la presión en los oídos.'),
('salidas', 'El viaje largo', [
 ('auto', 'Hoy viajamos en auto a la playa. El viaje es largo.'),
 ('silla', 'Me senté en mi asiento y papá me ayudó a abrochar el cinturón.'),
 ('reloj_espera', 'Al rato pregunté: "¿Falta mucho?". Mamá me mostró en el mapa cuánto faltaba.'),
 ('libro', 'Para pasar el tiempo, contamos autos rojos y escuchamos canciones.'),
 ('mano_arriba', 'Cuando tuve ganas de ir al baño, avisé, y paramos en un lugar.'),
 ('sol', 'Por fin vimos el mar por la ventana. ¡Llegamos!'),
 ('feliz', 'El viaje fue largo, pero valió la pena.'),
], 'Una "bolsa de viaje" con juguetes que solo se usan en el auto mantiene el interés.'),
('salidas', 'El cumpleaños de Valentina', [
 ('globo', 'Valentina, mi compañera, me invitó a su fiesta de cumpleaños.'),
 ('regalo', 'Con mamá elegimos un regalo: un libro de princesas, porque a ella le encantan.'),
 ('ruido', 'Al llegar, había globos, música fuerte y muchos niños corriendo.'),
 ('nervioso', 'Al principio me quedé cerca de mamá, mirando.'),
 ('amigos', 'Valentina vino a buscarme para jugar a la piñata. ¡Le pegué fuerte!'),
 ('pastel', 'Luego cantamos "Feliz cumpleaños" y comimos un pastel de chocolate.'),
 ('puerta', 'Cuando me cansé, salí un rato al patio con mamá a descansar.'),
 ('feliz', 'Al irnos, le dije a Valentina: "Gracias por invitarme". ¡Fue una gran fiesta!'),
], 'Llega temprano, cuando hay menos gente, y acuerda una señal por si necesita salir.'),
('salidas', 'Una tarde en el parque', [
 ('parque', 'Hoy hacía sol, así que fuimos al parque después del almuerzo.'),
 ('amigos', 'Había muchos niños jugando en los columpios y en el tobogán.'),
 ('fila', 'Esperé mi turno en el columpio. Cuando subí, sentí que volaba.'),
 ('adulto', 'Siempre me quedé en un lugar donde mamá podía verme.'),
 ('alarma', 'Mamá me avisó: "En cinco minutos nos vamos". Aproveché para tirarme una vez más.'),
 ('triste', 'Cuando fue la hora de irnos, me dio pena dejar el parque.'),
 ('feliz', 'Me despedí del parque con la mano. Podemos volver otro día.'),
], 'Usa un temporizador visible: "cuando suene, nos vamos". Avisa siempre antes del final.'),
('salidas', 'La cena en el restaurante', [
 ('restaurante', 'Hoy es el aniversario de mamá y papá, y fuimos a cenar a un restaurante.'),
 ('silla', 'Un señor muy amable nos llevó a nuestra mesa.'),
 ('libro', 'Mientras elegíamos la comida, yo pinté el mantel de papel con crayones.'),
 ('reloj_espera', 'La comida tardó un rato. Esperar sentado me costó, así que jugué al "veo, veo" con papá.'),
 ('plato', 'Por fin llegó mi plato: fideos con salsa. ¡Estaban riquísimos!'),
 ('corazon', 'Al terminar, le dije "gracias" al señor que nos atendió.'),
 ('feliz', 'Mamá y papá dijeron que fue una noche perfecta.'),
], 'Lleva una actividad tranquila para la espera y elige horarios con poca gente.'),
]
