"""35 ambientes decorados: (zona, código de plano, estilo, título, decoración, centro_x, [consejos], truco)."""

PALETA_NOMBRES = {
 'nordico': ['Blanco hueso', 'Salvia', 'Mostaza', 'Roble claro', 'Verde bosque'],
 'industrial': ['Cemento', 'Negro mate', 'Óxido', 'Nogal oscuro', 'Verde gris'],
 'rustico': ['Arena', 'Oliva', 'Terracota', 'Pino tostado', 'Chocolate'],
 'moderno': ['Gris perla', 'Azul noche', 'Naranja', 'Piedra', 'Acero'],
 'boho': ['Lino', 'Terracota', 'Oliva', 'Miel', 'Crudo'],
 'minimal': ['Blanco', 'Negro', 'Arena', 'Gris piedra', 'Gris azulado'],
 'infantil': ['Celeste', 'Rosa pastel', 'Menta', 'Madera clara', 'Verde hoja'],
 'tropical': ['Verde agua', 'Selva', 'Mango', 'Bambú', 'Coral'],
 'costero': ['Brisa', 'Azul marino', 'Blanco espuma', 'Arena', 'Sol'],
 'clasico': ['Marfil', 'Vino', 'Dorado', 'Nogal', 'Verde inglés'],
}

ZONAS = ['Sala', 'Comedor', 'Dormitorio', 'Cuarto infantil', 'Cocina', 'Baño', 'Recibidor', 'Estudio', 'Exterior']

A = [
# ------------------------------------------------------------------ SALA (7)
('Sala', 'SAL-01', 'nordico', 'Sala nórdica luminosa', [('alfombra',), ('cuadros_trio',), ('izq', 'planta_alta'), ('der', 'lampara_pie'), ('colgante', 830)], None,
 ['Paredes en blanco hueso para que la luz rebote y el espacio se vea más amplio.', 'Tres cuadros pequeños alineados a la misma altura sobre el mueble, centrados con la TV.', 'Una planta grande en la esquina aporta vida y suaviza las líneas rectas.', 'Alfombra redonda de tonos claros para delimitar la zona de estar.'],
 'Deja el nicho central casi vacío: 2 o 3 objetos bastan. El estilo nórdico respira.'),
('Sala', 'SAL-02', 'industrial', 'Rincón industrial con carácter', [('alfombra', 1.2), ('reloj', 840, 130), ('izq', 'farol'), ('der', 'planta_alta'), ('colgante', 300, 80)], None,
 ['Una pared de ladrillo (real o en papel tapiz) es la base del estilo industrial.', 'El grafito y el nogal del mueble combinan con metal negro y luz cálida.', 'Un reloj grande de pared funciona como pieza central.', 'Lámparas de foco visible y plantas de hojas oscuras completan el look.'],
 'Si no puedes tener ladrillo, pinta la pared de gris cemento y suma objetos de metal negro.'),
('Sala', 'SAL-07', 'minimal', 'Minimalismo flotante', [('cuadro', 240, 150, 0, 1), ('der', 'planta_peq', 40, -110)], None,
 ['Un mueble flotante deja ver el piso y hace que la sala parezca más grande.', 'Un solo cuadro grande dice más que muchos pequeños.', 'Mantén la superficie despejada: un libro, una vela y nada más.', 'Esconde los cables con canaletas pintadas del color de la pared.'],
 'Instálalo a 25–30 cm del piso: queda flotando y se limpia fácil por debajo.'),
('Sala', 'SAL-05', 'boho', 'Sala boho cálida', [('alfombra', 1.15), ('guirnalda', 180, 860, 30), ('espejo',), ('izq', 'cesto'), ('der', 'planta_alta')], None,
 ['Tonos tierra: terracota, miel y verde oliva crean un ambiente acogedor.', 'Un espejo redondo con marco de color sobre el mueble agranda la pared.', 'Cestos de fibra natural para guardar mantas y revistas.', 'Luces cálidas colgantes para las noches.'],
 'Mezcla texturas: madera, mimbre, lino y plantas. En el boho, lo hecho a mano suma.'),
('Sala', 'SAL-11', 'rustico', 'Mesa de centro de campo', [('alfombra', 1.6), ('ventana', 60), ('der', 'cojines', 40), ('izq', 'planta_peq', 30)], 560,
 ['La mesa de tablas de pino es la protagonista: déjala con su veta natural y cera.', 'Una alfombra grande que sobresalga de la mesa unifica el espacio.', 'Cojines en tonos tierra en el suelo para una sala relajada.', 'Cortinas de lino dejan pasar la luz y dan calidez.'],
 'Un acabado con cera o aceite resalta la madera y se repara fácil si se raya.'),
('Sala', 'SAL-15', 'tropical', 'Librero lleno de vida', [('macetas_colgantes', 640), ('izq', 'planta_alta'), ('der', 'cesto')], 470,
 ['Mezcla libros con plantas pequeñas en los estantes para romper la rigidez.', 'Verdes intensos y madera clara transmiten frescura.', 'Macetas colgantes para sumar plantas sin ocupar suelo.', 'Agrupa los libros por color: queda ordenado y decorativo.'],
 'Deja un 30 % de cada estante libre: así se ve decorado y no recargado.'),
('Sala', 'SAL-17', 'costero', 'Cubos de aire costero', [('ventana', 640), ('izq', 'planta_peq', 30), ('der', 'cesto', 20)], 420,
 ['Blanco y azul con rayas suaves en la pared evocan la playa.', 'Combina cubos abiertos con cestos para esconder el desorden.', 'Objetos de fibra natural, conchas y vidrio azul en los cubos.', 'Mucha luz natural y cortinas livianas.'],
 'Usa cajas de tela del mismo color en algunos cubos: ordena y da ritmo visual.'),
# --------------------------------------------------------------- COMEDOR (5)
('Comedor', 'COM-02', 'nordico', 'Comedor familiar nórdico', [('colgante', 520, 120), ('cuadro', 260, 130, -320, 1), ('izq', 'planta_alta', 10), ('alfombra', 1.05)], None,
 ['Una lámpara colgante sobre el centro de la mesa define el comedor.', 'La madera de pino natural con aceite incoloro mantiene el tono claro.', 'Un cuadro grande de paisaje en la pared lateral.', 'Una planta alta en la esquina equilibra el volumen de la mesa.'],
 'Cuelga la lámpara a 70–80 cm sobre la mesa: ilumina sin tapar la vista.'),
('Comedor', 'COM-06', 'rustico', 'Comedor de campo', [('colgante', 420, 110), ('colgante', 620, 110), ('ventana', 60), ('der', 'cesto')], 540,
 ['La mesa de tablas pide un acabado envejecido o con nudos a la vista.', 'Dos lámparas colgantes iguales para mesas largas.', 'Cestos de pan y frutas como centro de mesa.', 'Paredes cálidas y cortinas de lino.'],
 'Para envejecer la madera, lija los bordes y aplica tinte nogal con un trapo, retirando el exceso.'),
('Comedor', 'COM-08', 'industrial', 'Barra industrial', [('reloj', 160, 150), ('colgante', 440, 90), ('colgante', 580, 90), ('der', 'planta_alta')], 500,
 ['Una mesa alta funciona como comedor diario en espacios pequeños.', 'Lámparas de metal negro a distintas alturas.', 'Taburetes de madera y metal combinan con el ladrillo.', 'Una planta grande suaviza el ambiente.'],
 'Si la mesa queda contra la pared, gana espacio para dos personas más.'),
('Comedor', 'COM-17', 'clasico', 'Aparador elegante', [('espejo',), ('izq', 'lampara_pie'), ('der', 'planta_alta')], None,
 ['Sobre el aparador, un espejo grande refleja la luz del comedor.', 'Dos lámparas o candelabros simétricos dan elegancia.', 'Dentro, la vajilla de uso diario; encima, solo lo bonito.', 'Paredes con molduras pintadas en blanco y tonos vino.'],
 'La simetría es la clave del estilo clásico: lo que pongas a un lado, repítelo al otro.'),
('Comedor', 'COM-20', 'moderno', 'Rincón de café', [('repisa', 360, 170, 280), ('der', 'planta_peq', 20), ('izq', 'cesto', 20)], 520,
 ['El mueble bar se convierte en estación de café con cafetera y tazas a la vista.', 'Una repisa encima para frascos y tazas colgadas.', 'Grafito y roble con detalles en naranja, toque moderno.', 'Un cesto para cápsulas o bolsitas de té.'],
 'Pon un enchufe cerca del mueble antes de instalarlo: te ahorra cables a la vista.'),
# ------------------------------------------------------------ DORMITORIO (5)
('Dormitorio', 'DOR-14', 'nordico', 'Cómoda con estilo', [('cuadro', 200, 160, 0, 2), ('izq', 'planta_alta'), ('der', 'cesto'), ('alfombra', 1.1)], None,
 ['Una cómoda ancha también sirve como tocador o mesa de TV del cuarto.', 'Un cuadro grande apoyado o colgado centrado sobre ella.', 'Tiradores de cuero o madera para un toque artesanal.', 'Una alfombra suave al costado para pisar descalzo.'],
 'Usa cajas organizadoras dentro de los cajones: la ropa se ve y no se arruga.'),
('Dormitorio', 'DOR-20', 'boho', 'Tocador boho', [('espejo',), ('guirnalda', 220, 820, 30), ('izq', 'planta_alta'), ('der', 'cesto')], None,
 ['Un espejo redondo grande es el corazón del tocador.', 'Luces cálidas alrededor para maquillarse con buena luz.', 'Platitos de cerámica para anillos y aretes.', 'Plantas y cestos en tonos naturales.'],
 'Coloca el tocador cerca de una ventana: la luz natural es la mejor para arreglarse.'),
('Dormitorio', 'DOR-18', 'clasico', 'Ropero clásico', [('der', 'lampara_pie', 20), ('izq', 'planta_alta', 20), ('alfombra', 1.0)], 500,
 ['Un ropero amplio en roble ordena todo el cuarto.', 'Tiradores dorados o de bronce le dan un aire clásico.', 'Una lámpara de pie al lado para iluminar al vestirse.', 'Paredes en tonos marfil con zócalo blanco.'],
 'Pega un espejo de cuerpo entero en la cara interior de una puerta: no ocupa espacio.'),
('Dormitorio', 'DOR-09', 'minimal', 'Mesa de noche minimalista', [('cuadro', 140, 180, 0, 3), ('der', 'planta_peq', 20)], 470,
 ['Una mesa de noche simple con dos cajones: lo justo y necesario.', 'Encima, solo una lámpara pequeña y un libro.', 'Un cuadro vertical alto alarga visualmente la pared.', 'Colores neutros para un descanso tranquilo.'],
 'Si el cuarto es pequeño, usa la versión flotante (DOR-11): libera el piso.'),
('Dormitorio', 'DOR-15', 'moderno', 'Cómoda alta para espacios pequeños', [('cuadros_trio',), ('izq', 'planta_alta', 20), ('der', 'cesto', 20)], 460,
 ['Una cómoda alta guarda mucho ocupando poco ancho.', 'Gris humo con detalles en naranja y azul noche.', 'Cuadros pequeños para no recargar la pared.', 'Un cesto para la ropa sucia al lado.'],
 'Fija siempre las cómodas altas a la pared: evita que se vuelquen.'),
# --------------------------------------------------------- CUARTO INFANTIL (5)
('Cuarto infantil', 'INF-03', 'infantil', 'Cuarto de hermanos', [('banderines', 70, 560, 30), ('estrellas', 640, 80), ('nube', 700, 260), ('der', 'cesto')], 360,
 ['Una litera aprovecha el espacio y libera suelo para jugar.', 'Banderines y estrellas en la pared hacen el cuarto mágico.', 'Lunares blancos sobre celeste, un fondo alegre y calmo.', 'Un cesto grande para guardar peluches rápido.'],
 'Fija la litera a la pared y revisa que las barandas superiores estén bien firmes.'),
('Cuarto infantil', 'INF-06', 'infantil', 'Rincón de arte', [('repisa', 120, 200, 260), ('guirnalda', 520, 940, 40), ('der', 'planta_peq'), ('alfombra', 1.4)], 520,
 ['Una mesa infantil a su altura invita a dibujar y crear.', 'Una repisa con frascos de colores para los materiales.', 'Exhibe sus dibujos con una cuerda y pinzas en la pared.', 'Alfombra lavable bajo la mesa.'],
 'Pinta la pared con pintura de pizarra a la altura del niño: dibujará sin límites.'),
('Cuarto infantil', 'INF-11', 'infantil', 'Juguetes en orden', [('banderines', 250, 800, 20), ('nube', 120, 160), ('nube', 820, 200), ('izq', 'cesto'), ('alfombra', 1.2)], None,
 ['El organizador bajo deja todo al alcance de los niños.', 'Cajas de colores en los cubos: cada color, un tipo de juguete.', 'Etiquetas con dibujos para que ordenen solos.', 'Nubes y banderines para decorar la pared.'],
 'Rota los juguetes: guarda la mitad y cámbialos cada mes. Se aburren menos.'),
('Cuarto infantil', 'INF-13', 'infantil', 'Baúl de los tesoros', [('estrellas', 120, 90), ('cuadro', 160, 130, 0, 2), ('der', 'planta_peq'), ('izq', 'cesto')], None,
 ['El baúl con ruedas se mueve fácil para jugar en cualquier lugar.', 'La tapa también sirve como banco para sentarse.', 'Un cuadro con su nombre o una ilustración sobre el baúl.', 'Colores pastel que combinan con todo.'],
 'Instala bisagras de cierre lento en la tapa: protegen los dedos de los niños.'),
('Cuarto infantil', 'INF-16', 'nordico', 'Cambiador del bebé', [('repisa', 150, 210, 240), ('colgante', 760, 100), ('der', 'cesto'), ('alfombra', 1.1)], 520,
 ['El cambiador con cajonera tiene todo a mano: pañales, ropa y cremas.', 'Tonos suaves y naturales para un ambiente tranquilo.', 'Una repisa encima para lo que se usa a diario.', 'Luz cálida y suave para los cambios de noche.'],
 'Cuando ya no se use para cambiar, quita la baranda superior: queda una cómoda normal.'),
# --------------------------------------------------------------- COCINA (3)
('Cocina', 'COC-17', 'moderno', 'Isla de cocina moderna', [('colgante', 420, 100), ('colgante', 620, 100), ('der', 'planta_peq'), ('macetas_colgantes', 80)], 520,
 ['La isla con barra funciona como mesa de desayuno y zona de trabajo.', 'Dos colgantes iguales sobre la barra.', 'Taburetes altos del lado de la barra.', 'Hierbas en macetas colgantes: decoran y se usan.'],
 'Deja al menos 90 cm de paso alrededor de la isla para moverte cómodo.'),
('Cocina', 'COC-09', 'nordico', 'Cocina nórdica', [('utensilios', 330, 110, 380), ('repisa', 720, 160, 220), ('der', 'planta_peq')], 470,
 ['Blanco con frentes de color da una cocina luminosa y actual.', 'Una barra en la pared para colgar utensilios.', 'Repisas abiertas con frascos de vidrio.', 'Plantas aromáticas cerca de la ventana.'],
 'Usa frascos iguales para guardar granos: ordena y queda muy decorativo.'),
('Cocina', 'COC-19', 'tropical', 'Carrito auxiliar', [('macetas_colgantes', 620), ('izq', 'planta_alta'), ('repisa', 160, 210, 220)], 470,
 ['Un carrito con ruedas suma superficie donde la necesites.', 'Úsalo como barra de café, frutero o estación de cócteles.', 'Colores frescos y plantas para un aire tropical.', 'En la cocina pequeña, se guarda bajo la encimera.'],
 'Pon ruedas con freno: se mueve fácil y se queda quieto cuando trabajas encima.'),
# ------------------------------------------------------------------ BAÑO (3)
('Baño', 'BAN-02', 'costero', 'Baño costero', [('espejo',), ('der', 'cesto'), ('izq', 'planta_peq')], None,
 ['Blanco y azul con rayas suaves para un baño fresco.', 'Espejo redondo sobre el lavamanos.', 'Cestos de fibra para toallas enrolladas.', 'Una planta que tolere humedad, como un helecho.'],
 'Sella todos los cantos de la melamina con silicona: el agua es su enemigo.'),
('Baño', 'BAN-04', 'minimal', 'Baño minimalista flotante', [('espejo',), ('der', 'planta_peq', 30, -60)], None,
 ['El mueble flotante facilita limpiar el piso y agranda el baño.', 'Grafito y roble con grifería negra, elegante y sobrio.', 'Encima, solo jabón y una planta pequeña.', 'Toallas blancas o grises, nada más.'],
 'Instala el mueble a unos 50 cm del piso: el lavamanos queda a la altura correcta.'),
('Baño', 'BAN-19', 'boho', 'Estante spa', [('izq', 'planta_alta'), ('der', 'cesto'), ('guirnalda', 300, 760, 30)], 520,
 ['Un estante de listones convierte el baño en un spa.', 'Toallas enrolladas, velas y frascos de vidrio.', 'Plantas que aman la humedad: potus, helechos.', 'Tonos tierra y fibras naturales.'],
 'Usa pino tratado o barnízalo con barniz marino para resistir la humedad.'),
# ------------------------------------------------------------- RECIBIDOR (3)
('Recibidor', 'REC-08', 'nordico', 'Entrada nórdica', [('espejo',), ('izq', 'planta_alta'), ('der', 'cesto')], None,
 ['Una consola estrecha recibe a todos sin ocupar el paso.', 'Un espejo encima para la última mirada antes de salir.', 'Una bandeja para llaves y correo.', 'Un cesto debajo para bolsas o zapatos.'],
 'Con 25–30 cm de fondo basta: la entrada se siente amplia.'),
('Recibidor', 'REC-06', 'rustico', 'Banca zapatera de entrada', [('repisa', 280, 230, 440), ('der', 'planta_alta'), ('alfombra', 1.1)], 470,
 ['Sentarse para ponerse los zapatos y guardarlos en el mismo lugar.', 'Una repisa con colgadores encima para abrigos.', 'Cojín sobre la banca para mayor comodidad.', 'Alfombra resistente para limpiar los pies.'],
 'Asigna un cajón por persona: cada uno ordena lo suyo.'),
('Recibidor', 'REC-16', 'moderno', 'Recibidor organizado', [('izq', 'planta_alta', 20), ('cuadro', 180, 140, 330, 3), ('der', 'cesto', 20)], 400,
 ['Un armario de entrada guarda abrigos, zapatos y paraguas.', 'Las puertas cerradas mantienen la entrada siempre ordenada.', 'Un cuadro al lado da la bienvenida.', 'Una planta alta junto a la puerta.'],
 'Instala ganchos dentro de las puertas para mochilas y bolsos.'),
# ---------------------------------------------------------------- ESTUDIO (2)
('Estudio', 'EST-03', 'nordico', 'Home office nórdico', [('repisa', 300, 170, 260), ('ventana', 720), ('izq', 'planta_alta')], 470,
 ['Un escritorio con cajonera mantiene todo a mano.', 'Ubícalo cerca de la ventana para trabajar con luz natural.', 'Una repisa encima para libros y archivadores.', 'Una planta cerca reduce el estrés.'],
 'La luz natural debe llegar de costado, no de frente ni de espaldas, para no hacer reflejos en la pantalla.'),
('Estudio', 'EST-07', 'industrial', 'Escritorio industrial', [('reloj', 820, 140), ('repisa', 260, 190, 260), ('der', 'planta_alta'), ('colgante', 520, 70)], 500,
 ['La madera de pino en H con ladrillo de fondo, puro estilo taller.', 'Lámpara de metal negro de brazo o colgante.', 'Repisa con cajas de metal para organizar.', 'Un reloj grande de pared.'],
 'Aplica tinte nogal y cera negra en los bordes: la madera se ve antigua y robusta.'),
# --------------------------------------------------------------- EXTERIOR (2)
('Exterior', 'EXT-02', 'tropical', 'Terraza tropical', [('macetas_colgantes', 60), ('guirnalda', 300, 960, 30), ('der', 'planta_alta'), ('izq', 'farol')], 540,
 ['Una banca con respaldo para descansar al aire libre.', 'Cojines impermeables de colores vivos.', 'Plantas grandes y colgantes para un ambiente selvático.', 'Luces de guirnalda para las noches.'],
 'Usa pino tratado y renueva el aceite protector una vez al año.'),
('Exterior', 'EXT-14', 'rustico', 'Balcón de plantas', [('macetas_colgantes', 640), ('izq', 'cactus'), ('der', 'farol')], 460,
 ['El estante de 3 niveles multiplica el espacio para plantas.', 'Combina plantas colgantes, suculentas y aromáticas.', 'Macetas de barro para un toque rústico.', 'Un farol para iluminar de noche.'],
 'Pon las plantas que necesitan más sol arriba y las de sombra abajo.'),
]
